jobs:
  include:
    - stage: bundle audit && test
      language: ruby
      rvm: 2.4
      env:
        - RACK_ENV=test
      services:
        - mysql
      before_install:
        - openssl aes-256-cbc -K $encrypted_dee5a0b392fa_key -iv $encrypted_dee5a0b392fa_iv -in config/configs.tar.enc -out config/configs.tar -d
        - tar xvf config/configs.tar
      script:
        - bundle exec bundle-audit update && bundle exec bundle-audit check
        - bundle exec rake db:create
        - bundle exec rake db:migrate
        - bundle exec rspec
        - bundle exec rake coveralls:push
    - stage: staging
      language: minimal
      before_deploy:
        - openssl aes-256-cbc -K $encrypted_dee5a0b392fa_key -iv $encrypted_dee5a0b392fa_iv -in config/configs.tar.enc -out config/configs.tar -d
        - tar xvf config/configs.tar
        - git add -f config/app.yml
        - git add -f config/database.yml
        - git commit -m "Adds config files"
      deploy:
        provider: heroku
        app: sinatraapi-staging
        api_key:
          secure: "CAmYWq/XQMiMuoprHyABzM4BkiQuRXF6CeWfIQkv6gVfWdR4AIVTjsUpuqHLKmSPqv6H3fFaH3G9ynAC5auxD/5r3EsPXYMY2EOgCMfJpM/hvB2zWUbis+X3g+4Utlr6J/GV+UunZwpmPmsIs01D9JZo48WCFnsrhmMtgsUXShOjQyyTj6TvJhKdNIou44nShCIedW/TEqO/goNUtcLj5FD5RTuhuqow4dVzS7xanpM7rU5jQJ8DPrioiNGxo3PwFfTl5KUWDH3sJ5ffdYeobQ7FMZ10SRvWBGtnBWmQXhBR/ojlsuinH7awEDBv54ytoosqhB6oMK1loDj9UCYQkxgqU5aiofWDvzb56Yq0Tvkc39jwDxsAHZMRjNpl451I7oLFqPtEigN7SEzBNi2y5et2B2KZgtm3BmegFegcSWY1zw0ixX8lUBbdmQU34kMktHcoLwar0vawxkUd1j49tR3URwlWDR8/HqiQ2N6v72op7V+ftlv7TGQbSKTFp3apu9FVkj0OSCzcGbnyoClYWCj+mQPMoNX1VqkMu3VpRf8Jp++K0H6QQ/lYfOIWxoM6wW7AvTZKqneip4RNVdb8bU8lilwN/jKAlqXENeahMw8KG40ZT0sNpqS2QsoG/9ygfGvBY5PpuDH3nOtrVyD6WXesGP/PNbcxMBmDUhO2uNU="
        run:
          - "bundle exec rake db:migrate"
          - "bundle exec rake db:seed"
    - stage: smoke staging
      language: ruby
      rvm: 2.4
      script: ruby smoke_test/script.rb https://sinatraapi-staging.herokuapp.com
    - stage: production
      language: minimal
      before_deploy:
        - openssl aes-256-cbc -K $encrypted_dee5a0b392fa_key -iv $encrypted_dee5a0b392fa_iv -in config/configs.tar.enc -out config/configs.tar -d
        - tar xvf config/configs.tar
        - git add -f config/app.yml
        - git add -f config/database.yml
        - git commit -m "Adds config files"
      deploy:
        provider: heroku
        app: sinatraapi
        api_key:
          secure: "CAmYWq/XQMiMuoprHyABzM4BkiQuRXF6CeWfIQkv6gVfWdR4AIVTjsUpuqHLKmSPqv6H3fFaH3G9ynAC5auxD/5r3EsPXYMY2EOgCMfJpM/hvB2zWUbis+X3g+4Utlr6J/GV+UunZwpmPmsIs01D9JZo48WCFnsrhmMtgsUXShOjQyyTj6TvJhKdNIou44nShCIedW/TEqO/goNUtcLj5FD5RTuhuqow4dVzS7xanpM7rU5jQJ8DPrioiNGxo3PwFfTl5KUWDH3sJ5ffdYeobQ7FMZ10SRvWBGtnBWmQXhBR/ojlsuinH7awEDBv54ytoosqhB6oMK1loDj9UCYQkxgqU5aiofWDvzb56Yq0Tvkc39jwDxsAHZMRjNpl451I7oLFqPtEigN7SEzBNi2y5et2B2KZgtm3BmegFegcSWY1zw0ixX8lUBbdmQU34kMktHcoLwar0vawxkUd1j49tR3URwlWDR8/HqiQ2N6v72op7V+ftlv7TGQbSKTFp3apu9FVkj0OSCzcGbnyoClYWCj+mQPMoNX1VqkMu3VpRf8Jp++K0H6QQ/lYfOIWxoM6wW7AvTZKqneip4RNVdb8bU8lilwN/jKAlqXENeahMw8KG40ZT0sNpqS2QsoG/9ygfGvBY5PpuDH3nOtrVyD6WXesGP/PNbcxMBmDUhO2uNU="
        run:
          - "bundle exec rake db:migrate"
          - "bundle exec rake db:seed"
    - stage: smoke production
      language: ruby
      rvm: 2.4
      script: ruby smoke_test/script.rb https://sinatraapi.herokuapp.com